development: &dev
  adapter: mysql2
  host: localhost
  database: payments_exercise_development
  username: root
  password:
  readable: true
  reconnect: true
  pool: 25

test: &test
  adapter: mysql2
  database: payments_exercise_test
  username: root
  password:
